'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SCPSLSoundBoard.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient10() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient11() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient12() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient13() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient14() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient15() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient17() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient18() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient19() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient1a() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient1a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient20() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient21() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient22() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient23() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient2a() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient2a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient3a() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient3a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient4a() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient4a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient5a() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient5a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient6a() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient6a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient7a() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient7a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient8() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient8a() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient8a", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Ambient9() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Ambient9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Bell1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Bell1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Bell2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Bell2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Broadcast2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Broadcast2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Broadcast7() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Broadcast7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Canceled() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Canceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property EMPGrenade() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("EMPGrenade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property falldamage() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("falldamage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Helicopter() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Helicopter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property HIDTurret() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("HIDTurret", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ic_start() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ic_start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ic_stop() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ic_stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Main100() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Main100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Main110() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Main110", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Main120() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Main120", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Main80() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Main80", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Main90() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Main90", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property OutOfAmmo() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("OutOfAmmo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ReloadE11Rifle01() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ReloadE11Rifle01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ReloadE11Rifle02() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ReloadE11Rifle02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ReloadM249() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ReloadM249", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ReloadMicroUzi() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ReloadMicroUzi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ReloadPistol() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ReloadPistol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Resume100() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Resume100", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Resume30() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Resume30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Resume40() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Resume40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Resume50() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Resume50", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Resume60() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Resume60", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Resume70() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Resume70", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Resume80() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Resume80", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Resume90() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Resume90", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scare_0() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scare_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scare_1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scare_1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scare_2() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scare_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scare_3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scare_3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scare_4() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scare_4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scare_5() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scare_5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Scare_6() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scare_6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP096IdleSound() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP096IdleSound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP096Scream() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP096Scream", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP096Triggered() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP096Triggered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP106Contained() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP106Contained", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP106FemurBreaker() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP106FemurBreaker", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP106Footstep01() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP106Footstep01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP106Footstep02() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP106Footstep02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP106Footstep03() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP106Footstep03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP173Footstep01() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP173Footstep01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP173Footstep02() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP173Footstep02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP173Footstep03() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP173Footstep03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP173Snap01() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP173Snap01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP173Snap02() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP173Snap02", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SCP173Snap03() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SCP173Snap03", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ShotE11Rifle() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ShotE11Rifle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ShotMicroUzi() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ShotMicroUzi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ShotmM249() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ShotmM249", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property ShotPistol() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("ShotPistol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property SmokeGrenade() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("SmokeGrenade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property The_Chaos_Insurgency_Announce() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("The_Chaos_Insurgency_Announce", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
